import './globals.css';
import { Inter } from 'next/font/google';
import React, { ReactNode } from 'react';
import Loading from './components/Loading';
import Hero from './HeroPage/Hero';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode; // Typing the children prop explicitly
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <Loading/>
<Hero/>
        {children}
      </body>
    </html>
  );
}
